# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveSmallIntegerField(blank=True, verbose_name='Unit Number')),
                ('street', models.PositiveIntegerField(verbose_name='Street Number')),
                ('suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('state_province', models.CharField(max_length=40, verbose_name='State/Province')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_guide_api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_guide_api.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_guide_api.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='movies',
            field=models.ManyToManyField(through='cinema_guide_api.Showing', to='cinema_guide_api.Movie'),
        ),
    ]
