# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_guide_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_number',
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Street Name'),
            preserve_default=False,
        ),
    ]
