# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_guide_api', '0002_auto_20160605_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Unit Number'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, through='cinema_guide_api.Showing', to='cinema_guide_api.Movie'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
