# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_guide_api', '0003_auto_20160605_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Cinema ID'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='movies',
            field=models.ManyToManyField(blank=True, through='cinema_guide_api.Showing', to='cinema_guide_api.Movie'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cinema Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Movie ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Movie Name'),
        ),
    ]
