# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_guide_api', '0005_auto_20160606_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
