# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_guide_api', '0006_auto_20160606_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Cinema ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Movie ID'),
        ),
    ]
